#!/usr/bin/env python

if __name__ == "__main__":

  from gi.repository import Gtk, Gio
  from argonautics.ui import UI
  from argonautics.directory_filler import DirectoryFiller
  from argonautics.file_opener import FileOpener
  from argonautics.menu_sensitizer import MenuSensitizer
  from argonautics.deletion_prompter import DeletionPrompter
  import os
  import sys

  if len(sys.argv) > 1:
    directory_path = sys.argv[1]
  else:
    directory_path = os.getcwd()

  directory = Gio.file_new_for_commandline_arg(directory_path)
  storage = Gtk.ListStore
  directory_filler = DirectoryFiller(storage,directory)

  builder = Gtk.Builder()
  file_opener = FileOpener
  menu_sensitizer = MenuSensitizer
  deletion_prompter = DeletionPrompter

  ui = UI(builder, file_opener, menu_sensitizer, deletion_prompter)


  ui.setup_file_icons(directory_filler.get_store())
  ui.setup_signals()
  ui.desensitize_file_menu()

  ui.directory_window.show_all()
  Gtk.main()
