#!/usr/bin/env python

if __name__ == "__main__":

  from gi.repository import Gtk, Gio
  from argonautics.ui import UI
  from argonautics.directory_filler import DirectoryFiller
  from argonautics.file_manager import FileManager
  from argonautics.menu_sensitizer import MenuSensitizer
  import os


  directory = Gio.file_new_for_commandline_arg(os.getcwd())
  storage = Gtk.ListStore
  directory_filler = DirectoryFiller(storage,directory)

  builder = Gtk.Builder()
  file_manager = FileManager
  menu_sensitizer = MenuSensitizer

  ui = UI(builder, file_manager, menu_sensitizer)


  ui.setup_file_icons(directory_filler.get_store())
  ui.setup_signals()
  ui.desensitize_file_menu()

  ui.directory_window.show_all()
  Gtk.main()
